window.REVISTA_CONFIG = {
  nombre: "Revista Brisas",
  masthead: "Brisas",
  lema: "Cada lector, un socio permanente",
  lugar: "Don Torcuato, Tigre, Buenos Aires",
  url: "https://servi-net.com.ar/revista-don-torcuato",
  email: "revistabrisas@yahoo.com.ar",
  whatsapp: "5491150489366",
  instagram: "revistabrisas",
  facebook: "revistabrisas",
  telefono: "11 5048-9366",
  direccion: "Chacabuco 1909 (1611), Don Torcuato",
  suscribirUrl: "api/suscribir.php",
  pdfEdicion: "ediciones/brisas-369.pdf",
};
