window.REVISTA_DATA = {
  edicion: {
    numero: 1,
    mes: "Septiembre",
    anio: 2026,
    titulo: "Primavera en el barrio",
    bajada:
      "La revista digital de Don Torcuato: editorial, índice de anunciantes, clasificados y el buscador de profesionales para compartir por WhatsApp y email.",
    fecha: "Septiembre de 2026",
    cierreProxima: "Consultar",
    portadaTema: "primavera",
  },

  nav: [
    { href: "index.html", label: "Inicio", page: "home" },
    { href: "edicion.html", label: "Edición", page: "edicion" },
    { href: "actualidad.html", label: "Editorial", page: "actualidad" },
    { href: "indice.html", label: "Índice", page: "indice" },
    { href: "comercios.html", label: "Comercios", page: "comercios" },
    { href: "profesionales.html", label: "Profesionales", page: "profesionales" },
    { href: "clasificados.html", label: "Clasificados", page: "clasificados" },
    { href: "eventos.html", label: "Agenda", page: "eventos" },
    { href: "anunciantes.html", label: "Anunciantes", page: "anunciantes" },
    { href: "recibir.html", label: "Recibir", page: "recibir" },
  ],

  secciones: [
    { id: "editorial", nombre: "Editorial", desc: "La palabra de la edición.", href: "actualidad.html" },
    { id: "indice", nombre: "Índice", desc: "Quién anuncia y dónde encontrarlo.", href: "indice.html" },
    { id: "comercios", nombre: "Comercios", desc: "Guía de negocios para comprar cerca.", href: "comercios.html" },
    { id: "profesionales", nombre: "Profesionales", desc: "Médicos, oficios y estudios del barrio.", href: "profesionales.html" },
    { id: "clasificados", nombre: "Clasificados", desc: "Se busca, se alquila, se ofrece.", href: "clasificados.html" },
    { id: "eventos", nombre: "Agenda", desc: "Ferias, clubes y talleres.", href: "eventos.html" },
  ],

  articulos: [
    {
      id: "editorial-septiembre",
      seccion: "editorial",
      kicker: "Editorial · Edición 01",
      titulo: "El barrio se lee mejor cuando se comparte",
      bajada:
        "Esta edición digital nace para lo mismo que una revista de papel en Don Torcuato: que el aviso, el profesional y la nota circulen de vecino a vecino.",
      cuerpo: [
        "En Don Torcuato las noticias siguen viajando como siempre: un recorte en el kiosco, un aviso en la vidriera, un mensaje al grupo de WhatsApp de la manzana. Esta revista se arma con esa costumbre.",
        "Tomamos el orden que ya entiende el barrio —editorial, índice de anunciantes, profesionales, clasificados— y lo pasamos a la web. Así se publica en el hosting y se reparte por mail, WhatsApp y el resto de los medios.",
        "El índice no es un adorno: es para que un vecino encuentre al contador, la farmacia o el taller sin dar vueltas. Los clasificados son cortos, con teléfono a la vista. La editorial abre cada número, como en el papel.",
        "Si tenés un comercio, un estudio o un oficio, este es el lugar. Si querés recibir la edición, dejá el mail o el WhatsApp. El barrio se lee mejor cuando se reenvía.",
      ],
      autor: "Redacción TORCUATO",
      destacado: true,
      portada: true,
      tiempo: "4 min",
    },
    {
      id: "guia-estacion",
      seccion: "barrio",
      kicker: "Barrio",
      titulo: "La estación como plaza: qué hay a cinco minutos del tren",
      bajada:
        "Farmacia, panadería, kiosco y el café de siempre. Un recorrido útil para quien baja en Don Torcuato.",
      cuerpo: [
        "La estación sigue siendo el punto donde el barrio se encuentra. No es solo el andén: es el cruce de quienes van a Capital, de quienes vuelven del laburo y de quienes hacen el recado de la tarde.",
        "En un radio corto conviven oficios, comercios de cercanía y consultorios. Esa densidad es la que ordenamos en el índice de anunciantes: no para inventar un centro comercial, sino para que se vea lo que ya existe.",
        "Si llegás en tren un sábado, la recomendación es simple: caminá, mirá vidrieras y preguntá. El dato que no está en el mapa suele estar en el mostrador de al lado.",
      ],
      autor: "Lucía Pereyra",
      destacado: true,
      tiempo: "4 min",
    },
    {
      id: "como-anunciar",
      seccion: "editorial",
      kicker: "Anunciantes",
      titulo: "Cómo entrar al índice: un aviso que se reenvía",
      bajada:
        "El clasificado, la ficha profesional y el módulo destacado. El mismo esquema de una revista de barrio, ahora también digital.",
      cuerpo: [
        "En las revistas de papel de la zona el aviso no se improvisa: hay clasificado, ficha de profesional e índice para ubicar a cada anunciante. Acá repetimos esa lógica.",
        "El clasificado es corto y tiene teléfono. La ficha entra al buscador y al índice. El módulo destacado sale en la home y en la edición que se comparte.",
        "No hace falta una agencia. Hace falta un nombre, tres renglones y un WhatsApp. El resto se arma para que se vea como revista.",
      ],
      autor: "Comercial TORCUATO",
      destacado: false,
      tiempo: "3 min",
    },
    {
      id: "feria-primavera",
      seccion: "eventos",
      kicker: "Agenda",
      titulo: "La feria de primavera vuelve con productores y oficios",
      bajada:
        "Emprendimientos del Norte, huerta e indumentaria. La agenda viaja con la edición.",
      cuerpo: [
        "Septiembre tiene un ancla: la feria de primavera. Se va a comprar y se termina charlando.",
        "Si organizás un evento en un club, una escuela o una plaza, mandalo: sale en Agenda y en el envío que se reenvía.",
      ],
      autor: "Redacción TORCUATO",
      destacado: true,
      tiempo: "3 min",
    },
  ],

  comercios: [
    {
      id: "panaderia-anden",
      nombre: "Panadería El Andén",
      rubro: "Gastronomía",
      dest: true,
      dir: "Almirante Brown 1840, Don Torcuato",
      horario: "Lun a Dom 6 a 13 y 16 a 21",
      tel: "11 4444-1101",
      wa: "5491144441101",
      desc: "Facturas al horno, pan de campo y el café de la mañana junto a la estación.",
    },
    {
      id: "ferreteria-ford",
      nombre: "Ferretería Don Henry",
      rubro: "Hogar y oficio",
      dest: true,
      dir: "Av. Henry Ford 2450, Don Torcuato",
      horario: "Lun a Vie 8:30 a 18 · Sáb 8:30 a 13",
      tel: "11 4444-2202",
      wa: "5491144442202",
      desc: "Bulonería, herramientas y corte. Presupuesto por WhatsApp.",
    },
    {
      id: "farmacia-reconquista",
      nombre: "Farmacia Reconquista",
      rubro: "Salud",
      dest: true,
      dir: "Av. Reconquista 1200, Don Torcuato",
      horario: "Lun a Sáb 8 a 22 · Dom 9 a 14",
      tel: "11 4444-3303",
      wa: "5491144443303",
      desc: "Obra social, dermocosmética y delivery al barrio.",
    },
    {
      id: "dietetica-norte",
      nombre: "Dietética Norte Chico",
      rubro: "Almacén",
      dest: false,
      dir: "Italia 890, Don Torcuato",
      horario: "Lun a Sáb 9 a 13 y 16 a 20",
      tel: "11 4444-4404",
      wa: "5491144444404",
      desc: "Granel, sin TACC y productos para la semana.",
    },
    {
      id: "taller-mecanica",
      nombre: "Taller Mecánica Sur",
      rubro: "Automotriz",
      dest: false,
      dir: "Ruta 202 km 18, Don Torcuato",
      horario: "Lun a Vie 8 a 18 · Sáb 8 a 13",
      tel: "11 4444-5505",
      wa: "5491144445505",
      desc: "Service, frenos y diagnóstico.",
    },
    {
      id: "salon-primavera",
      nombre: "Salón Primavera",
      rubro: "Belleza",
      dest: false,
      dir: "Chile 560, Don Torcuato",
      horario: "Mar a Sáb 9 a 19",
      tel: "11 4444-6606",
      wa: "5491144446606",
      desc: "Peluquería, color y uñas.",
    },
    {
      id: "libreria-pino",
      nombre: "Librería Los Pinos",
      rubro: "Educación",
      dest: false,
      dir: "San Martín 2100, Don Torcuato",
      horario: "Lun a Vie 9 a 13 y 15 a 19",
      tel: "11 4444-7707",
      wa: "5491144447707",
      desc: "Útiles, fotocopias y listas de colegios.",
    },
    {
      id: "veterinaria-loma",
      nombre: "Veterinaria La Loma",
      rubro: "Mascotas",
      dest: true,
      dir: "Av. del Golf 340, Don Torcuato",
      horario: "Lun a Sáb 9:30 a 19",
      tel: "11 4444-8808",
      wa: "5491144448808",
      desc: "Clínica, vacunas y alimento.",
    },
  ],

  profesionales: [
    {
      id: "dra-benitez",
      nombre: "Dra. Carolina Benítez",
      oficio: "Pediatría",
      rubro: "Salud",
      dest: true,
      busca: "médico medica pediatra doctor chicos",
      zona: "Cerca de estación",
      dir: "Consultorio en Av. Reconquista, Don Torcuato",
      mat: "MN 128.440",
      wa: "5491150010001",
      desc: "Controles, vacunas y seguimiento escolar.",
    },
    {
      id: "estudio-roldan",
      nombre: "Estudio Roldán",
      oficio: "Contador público",
      rubro: "Estudios",
      dest: true,
      busca: "contador monotributo",
      zona: "Henry Ford",
      dir: "Av. Henry Ford 1980, Don Torcuato",
      mat: "CPCE",
      wa: "5491150010002",
      desc: "Monotributo, sociedades y liquidaciones para comercios.",
    },
    {
      id: "arq-molina",
      nombre: "Arq. Diego Molina",
      oficio: "Arquitectura y obra",
      rubro: "Oficios",
      dest: true,
      busca: "arquitecto planos",
      zona: "Barrios cerrados y casco",
      dir: "Don Torcuato y Tigre",
      mat: "CAPBA 1",
      wa: "5491150010003",
      desc: "Refacciones, planos y dirección de obra.",
    },
    {
      id: "elec-perez",
      nombre: "Javier Pérez",
      oficio: "Electricista matriculado",
      rubro: "Oficios",
      dest: false,
      busca: "luz tablero",
      zona: "Todo Don Torcuato",
      dir: "Domicilio y comercios",
      mat: "Mat. CABA/PBA",
      wa: "5491150010004",
      desc: "Tableros, cortocircuitos y certificación.",
    },
    {
      id: "abog-silva",
      nombre: "Dra. Elena Silva",
      oficio: "Abogada · Familia y laboral",
      rubro: "Estudios",
      dest: false,
      busca: "abogada laboral",
      zona: "Tigre y Zona Norte",
      dir: "Estudio en Don Torcuato",
      mat: "T° XII F° 88",
      wa: "5491150010005",
      desc: "Consultas en el estudio o por videollamada.",
    },
    {
      id: "plom-ruiz",
      nombre: "Héctor Ruiz",
      oficio: "Plomería y gas",
      rubro: "Oficios",
      dest: true,
      busca: "plomero gasista",
      zona: "Don Torcuato y Ricardo Rojas",
      dir: "Servicio a domicilio",
      mat: "Gasista 2da categoría",
      wa: "5491150010007",
      desc: "Pérdidas, termotanque y cañerías.",
    },
  ],

  clasificados: [
    {
      id: "c1",
      tipo: "Alquiler",
      titulo: "Departamento 2 ambientes cerca de la estación",
      texto: "Luminoso, planta baja, patio chico. Ideal pareja. Entrada inmediata.",
      contacto: "11 5001-2010",
      dest: true,
    },
    {
      id: "c2",
      tipo: "Venta",
      titulo: "Ford Ka 2018, único dueño",
      texto: "110.000 km, service al día. Se entrega en Don Torcuato.",
      contacto: "11 5001-2011",
      dest: false,
    },
    {
      id: "c3",
      tipo: "Se busca",
      titulo: "Niñera para dos chicos, tardes de lunes a jueves",
      texto: "Zona golf. Referencias excluyentes. Octubre.",
      contacto: "11 5001-2013",
      dest: false,
    },
    {
      id: "c4",
      tipo: "Empleo",
      titulo: "Mozo/a para confitería de Henry Ford",
      texto: "Turno tarde, experiencia en mostrador.",
      contacto: "11 5001-2014",
      dest: true,
    },
    {
      id: "c5",
      tipo: "Servicio",
      titulo: "Jardinería y corte de césped por manzana",
      texto: "Mantenimiento mensual de fondos y frentes.",
      contacto: "11 5001-2012",
      dest: false,
    },
    {
      id: "c6",
      tipo: "Servicio",
      titulo: "Costura y arreglos de indumentaria",
      texto: "Dobladillos, cierres y uniformes escolares. Retiro en el barrio.",
      contacto: "11 5001-2015",
      dest: false,
    },
    {
      id: "c7",
      tipo: "Se busca",
      titulo: "Mascota perdida en el casco",
      texto: "Si la viste, escribí. Publicamos el aviso en la edición y en la web.",
      contacto: "11 1234-5678",
      dest: false,
    },
  ],

  eventos: [
    {
      id: "e1",
      fecha: "Sáb 13 sep",
      hora: "10 a 18",
      titulo: "Feria de primavera",
      lugar: "Plaza cercana a la estación",
      desc: "Productores, indumentaria, huerta y patio de comidas.",
    },
    {
      id: "e2",
      fecha: "Jue 18 sep",
      hora: "19:00",
      titulo: "Charla de monotributo para comercios",
      lugar: "Salón de Estudio Roldán",
      desc: "Inscripción por WhatsApp de la revista.",
    },
    {
      id: "e3",
      fecha: "Sáb 20 sep",
      hora: "16:00",
      titulo: "Cuentos en la librería",
      lugar: "Librería Los Pinos",
      desc: "Lectura para chicos de 4 a 8.",
    },
  ],

  paquetes: [
    {
      id: "clasificado",
      nombre: "Clasificado",
      precio: "Consultar",
      detalle: "Como en el papel: 40 palabras, una categoría y teléfono. Sale en la web y en el envío.",
      items: ["Se busca / Alquiler / Servicio / Empleo", "Teléfono o WhatsApp", "15 días", "Entra al índice si es destacado"],
    },
    {
      id: "ficha",
      nombre: "Ficha en el índice",
      precio: "Consultar",
      detalle: "Tu nombre en el índice de anunciantes, con rubro y contacto.",
      items: ["Orden alfabético", "Rubro", "WhatsApp", "Link a tu ficha"],
    },
    {
      id: "destacado",
      nombre: "Módulo de edición",
      precio: "Consultar",
      detalle: "Recuadro en la sección (comercios, profesionales o clasificados).",
      items: ["Diseño incluido", "Prioridad en el listado", "Mención en el mail", "Un mes"],
    },
    {
      id: "portada",
      nombre: "Destacado de portada",
      precio: "Consultar",
      detalle: "La primera impresión de quien abre la revista o el enlace.",
      items: ["Home + edición", "Índice destacado", "Envío WhatsApp", "Reporte de clics"],
    },
  ],

  anunciantes: [
    { nombre: "Ferretería Don Henry", rubro: "Hogar y oficio", tipo: "Módulo", seccion: "Comercios", tel: "11 4444-2202" },
    { nombre: "Farmacia Reconquista", rubro: "Salud", tipo: "Portada", seccion: "Comercios", tel: "11 4444-3303" },
    { nombre: "Estudio Roldán", rubro: "Estudios", tipo: "Ficha", seccion: "Profesionales", tel: "11 5001-0002" },
    { nombre: "Veterinaria La Loma", rubro: "Mascotas", tipo: "Destacado", seccion: "Comercios", tel: "11 4444-8808" },
    { nombre: "Dra. Carolina Benítez", rubro: "Salud", tipo: "Ficha", seccion: "Profesionales", tel: "11 5001-0001" },
    { nombre: "Héctor Ruiz", rubro: "Oficios", tipo: "Ficha", seccion: "Profesionales", tel: "11 5001-0007" },
  ],
};
