window.REVISTA_DATA = {
  edicion: {
    numero: 1,
    mes: "Septiembre",
    anio: 2026,
    titulo: "El teatro, los jardines y el barrio",
    bajada:
      "Notas de septiembre en Don Torcuato: el Teatro Municipal, Tigres Lectores, el Jardín 922 y una guía de profesionales, farmacias y clasificados.",
    fecha: "12 de septiembre de 2026",
    cierreProxima: "Consultar",
    portadaTema: "primavera",
  },

  nav: [
    { href: "index.html", label: "Inicio", page: "home" },
    { href: "edicion.html", label: "Edición", page: "edicion" },
    { href: "actualidad.html", label: "Actualidad", page: "actualidad" },
    { href: "farmacias.html", label: "Farmacias", page: "farmacias" },
    { href: "indice.html", label: "Índice", page: "indice" },
    { href: "profesionales.html", label: "Profesionales", page: "profesionales" },
    { href: "clasificados.html", label: "Clasificados", page: "clasificados" },
    { href: "eventos.html", label: "Agenda", page: "eventos" },
    { href: "recibir.html", label: "Recibir", page: "recibir" },
  ],

  secciones: [
    { id: "actualidad", nombre: "Actualidad", desc: "Lo que pasa esta semana en Don Torcuato.", href: "actualidad.html" },
    { id: "farmacias", nombre: "Farmacias", desc: "Locales del barrio y el turno oficial de Tigre.", href: "farmacias.html" },
    { id: "indice", nombre: "Índice", desc: "Quién anuncia y dónde encontrarlo.", href: "indice.html" },
    { id: "profesionales", nombre: "Profesionales", desc: "Hospital, centros de salud, odontólogos y oficios.", href: "profesionales.html" },
    { id: "clasificados", nombre: "Clasificados", desc: "Agenda, empleos y avisos del barrio.", href: "clasificados.html" },
    { id: "eventos", nombre: "Agenda", desc: "Teatro, jardines, microestadio y lectura.", href: "eventos.html" },
  ],

  articulos: [
    {
      id: "teatro-municipal",
      seccion: "actualidad",
      kicker: "Portada · Edición 01",
      titulo: "El Teatro Municipal toma forma frente a Plaza Alvear",
      bajada:
        "Estrada y Camacuá. 1.200 m² y sala para más de 250 espectadores. En septiembre el municipio volvió a recorrer la obra.",
      cuerpo: [
        "Don Torcuato va a tener teatro propio. El edificio se levanta en Estrada y Camacuá, frente a Plaza Alvear: 1.200 metros cuadrados, auditorio para más de 250 espectadores, camarines y sanitarios. El municipio también adelantó que el predio puede sumar un espacio para el Museo de Don Torcuato.",
        "El 7 de septiembre el intendente Julio Zamora supervisó el avance. Dijo que construir estos espacios es una política de Estado y que la obra, junto al microestadio, va a servir a chicos, jóvenes e instituciones educativas. En paralelo, Tigre construye otro teatro en El Talar.",
        "Más temprano, en junio, el municipio ya había mostrado la sala en etapa de terminaciones, con artistas invitados. Los plazos oficiales hablan de una inauguración cercana. Hasta entonces, el dato útil para el barrio es la dirección: Estrada y Camacuá, frente a la plaza.",
        "Si un club, una escuela o un elenco local quiere enterarse de la apertura, esta revista lo va a publicar en la Agenda. El aviso, como el resto de la edición, se reenvía.",
      ],
      autor: "Redacción TORCUATO",
      destacado: true,
      portada: true,
      tiempo: "5 min",
      imagen: "img/notas/teatro-municipal.jpg",
      alt: "Ilustración del teatro municipal en obra junto a una plaza de barrio.",
      fuente: "La Noticia Web, 7 sep 2026 · Tigre Digital · InfoBAN",
    },
    {
      id: "tigres-lectores",
      seccion: "actualidad",
      kicker: "Educación",
      titulo: "Tigres Lectores llegó al Jardín 921 con una biblioteca móvil",
      bajada:
        "El 10 de septiembre entregaron el mueble «Entre Planetas, con un Libro en la Mano» y ejemplares infantiles. Ya van 44 entregas en el distrito.",
      cuerpo: [
        "La secretaria de Educación y Promoción Social, Gisela Zamora, encabezó la entrega en el Jardín de Infantes N° 921 de Don Torcuato. La mañana empezó con un taller de lectura y siguió con el mueble rodante y libros para el aula.",
        "Gisela Zamora dijo que estos encuentros acercan al chico y al adulto, amplían el vocabulario y ayudan a poner en palabras las emociones. El municipio impulsa la lectura desde el nivel inicial, en la escuela y en la casa.",
        "La vicedirectora Gabriela Rolón agradeció el recurso y pidió seguir generando momentos con las familias. La línea se llama Animación a la Lectura y forma parte de Tigres Lectores, en marcha desde 2023. En el mismo circuito también hubo entrega en el Jardín N° 949 de Rincón de Milberg.",
        "Si tu jardín o tu escuela recibió una biblioteca y querés que figure en la Agenda, escribinos. Publicamos el dato y el barrio lo reenvía.",
      ],
      autor: "Redacción TORCUATO",
      destacado: true,
      tiempo: "4 min",
      imagen: "img/notas/tigres-lectores.jpg",
      alt: "Ilustración de un jardín de infantes con una biblioteca móvil y niños leyendo.",
      fuente: "Tigre Digital, 10 sep 2026",
    },
    {
      id: "jardin-922",
      seccion: "barrio",
      kicker: "Barrio",
      titulo: "El Jardín 922 suma un SUM de 120 metros y patio nuevo",
      bajada:
        "El 8 de septiembre el municipio recorrió la obra: salón de usos múltiples, cocina y patio. En la Primaria 45 ya terminaron el comedor.",
      cuerpo: [
        "En el Jardín de Infantes N° 922 de Don Torcuato avanza un Salón de Usos Múltiples de 120 metros cuadrados. La obra incluye la cocina y el patio exterior. Gisela Zamora recorrió el predio con el equipo directivo el 8 de septiembre.",
        "El mismo plan de mantenimiento escolar pasó por El Talar y cerró el recambio de la cocina-comedor de la Escuela Primaria N° 45, con entrega de insumos para el personal auxiliar.",
        "Son obras chicas si se las mira desde afuera y grandes si se tiene un hijo en la sala. Por eso las publicamos con dirección y fecha, como se hace en una revista de papel.",
      ],
      autor: "Redacción TORCUATO",
      destacado: true,
      tiempo: "3 min",
      imagen: "img/notas/jardin-sum.jpg",
      alt: "Ilustración de un jardín de infantes con un salón nuevo y patio.",
      fuente: "Tigre Digital, 8 sep 2026",
    },
    {
      id: "microestadio-ubieto",
      seccion: "eventos",
      kicker: "Agenda",
      titulo: "El microestadio Ubieto ya es la cancha cubierta del barrio",
      bajada:
        "Polideportivo San Martín, Riobamba 2497. 1.600 m² y mil espectadores. Ahí se juega, se ve humor y se junta el barrio.",
      cuerpo: [
        "El microestadio municipal Intendente Cdor. Ricardo Ubieto funciona en el Polideportivo San Martín, Riobamba 2497. Tiene 1.600 metros cuadrados, capacidad para mil personas, vestuarios y tribunas. Se construyó con fondos municipales y lleva el nombre de quien impulsó el polideportivo en 1990.",
        "No es un anuncio a futuro: el predio ya se usa. En el ciclo Humor en los Barrios el municipio programó funciones gratuitas ahí. Si hay una fecha nueva de octubre, la cargamos en la Agenda apenas se publique.",
        "Para el vecino el dato corto es este: Riobamba 2497, Don Torcuato. Para el club o la escuela que necesita un techo, el contacto pasa por el municipio.",
      ],
      autor: "Redacción TORCUATO",
      destacado: true,
      tiempo: "3 min",
      imagen: "img/notas/microestadio.jpg",
      alt: "Ilustración del interior de un microestadio municipal.",
      fuente: "Tigre Digital · CINCO TV",
    },
    {
      id: "guia-salud-barrio",
      seccion: "profesionales",
      kicker: "Profesionales",
      titulo: "Dónde atenderse: HDI, centros de salud y farmacias de Alvear",
      bajada:
        "El Hospital Floreal Ferrara está en Colectora Oeste y Menéndez y Pelayo. En Alvear se alinean farmacias con teléfono publicado.",
      cuerpo: [
        "El Hospital Municipal de Diagnóstico Inmediato Dr. Floreal Ferrara funciona en Colectora Oeste y Menéndez y Pelayo. El municipio publica guardia y estudios; los turnos por WhatsApp figuran como 11 2689-9228 y 11 2031-0388. El teléfono de mesa es 011 4014-4484.",
        "La atención primaria del casco pasa por el Centro de Salud Don Torcuato (Arata y España, 11 4513-2533), el CAPS Belgrano (Gral. Belgrano 1661) y el Centro de Salud Baires (Blandengues, 11 4513-2532). La Clínica Sagrado Corazón, privada, está en Av. Alvear 650, 11 4741-7070.",
        "Sobre Alvear y Triunvirato hay farmacias con domicilio y teléfono en directorios públicos: Magnin, Castelli, Del Águila, Javi, Moroni, JKS. El turno del día se consulta en tigre.gob.ar/salud/farmacias. Llamá antes de ir.",
        "En esta guía no inventamos fichas: si el dato no está publicado, no entra. Si tu consultorio está y no figura, escribinos.",
      ],
      autor: "Redacción TORCUATO",
      destacado: false,
      tiempo: "4 min",
      imagen: "img/notas/guia-salud.jpg",
      alt: "Ilustración de una calle con farmacia y consultorio de barrio.",
    },
    {
      id: "editorial-septiembre",
      seccion: "editorial",
      kicker: "Editorial · Edición 01",
      titulo: "El barrio se lee mejor cuando se comparte",
      bajada:
        "Esta edición digital nace para lo mismo que una revista de papel: que la nota, el profesional y el aviso circulen de vecino a vecino.",
      cuerpo: [
        "En Don Torcuato las noticias siguen viajando como siempre: un recorte en el kiosco, un aviso en la vidriera, un mensaje al grupo de WhatsApp de la manzana. Esta revista se arma con esa costumbre.",
        "Tomamos el orden que ya entiende el barrio —editorial, actualidad, índice, profesionales, clasificados— y lo pasamos a la web. Las notas de este número son de septiembre: el teatro, los jardines, el microestadio. Las fichas salen de directorios y sitios públicos.",
        "El índice no es un adorno: es para encontrar el hospital, la farmacia o el odontólogo sin dar vueltas. Los clasificados mezclan agenda, empleos publicados y espacios para el aviso del vecino.",
        "Si tenés un comercio, un estudio o un oficio, este es el lugar. Si querés recibir la edición, dejá el mail o el WhatsApp.",
      ],
      autor: "Redacción TORCUATO",
      destacado: false,
      tiempo: "3 min",
      imagen: "img/notas/editorial-estacion.jpg",
      alt: "Ilustración de la estación de Don Torcuato al atardecer.",
    },
  ],

  comercios: [
    {
      id: "farmacia-magnin",
      nombre: "Farmacia Magnin",
      rubro: "Salud",
      dest: true,
      dir: "Triunvirato 1851 / 1875, Don Torcuato",
      horario: "Consultá horario en el local",
      tel: "11 4748-4605",
      desc: "Farmacia del casco, sobre Triunvirato. Teléfono publicado en directorios.",
    },
    {
      id: "farmacia-castelli",
      nombre: "Farmacia Castelli",
      rubro: "Salud",
      dest: true,
      dir: "Av. Alvear / Ruta 202 N° 2767, Don Torcuato",
      horario: "Consultá turno en tigre.gob.ar/salud/farmacias",
      tel: "11 4748-0460",
      desc: "Figura en el listado municipal de farmacias de turno. También 11 4748-4350.",
    },
    {
      id: "farmacia-aguila",
      nombre: "Farmacia Del Águila",
      rubro: "Salud",
      dest: true,
      dir: "Av. Ángel Torcuato de Alvear 2992, Don Torcuato",
      horario: "Lun a Sáb 8 a 21",
      tel: "11 5958-1236",
      desc: "Sobre Alvear. Horario publicado en directorios del barrio.",
    },
    {
      id: "farmacia-javi",
      nombre: "Farmacia Javi",
      rubro: "Salud",
      dest: false,
      dir: "Triunvirato 3102, Don Torcuato",
      horario: "Consultá en el local",
      tel: "11 4748-0645",
      desc: "Farmacia sobre Triunvirato, con teléfono publicado.",
    },
    {
      id: "farmacia-jks",
      nombre: "Farmacia JKS",
      rubro: "Salud",
      dest: false,
      dir: "Av. Ángel Torcuato de Alvear 602, Don Torcuato",
      horario: "Lun a Sáb 8 a 20:30",
      tel: "",
      desc: "Sobre Alvear. Confirmá el teléfono en el local.",
    },
    {
      id: "farmacia-moroni",
      nombre: "Farmacia Moroni",
      rubro: "Salud",
      dest: false,
      dir: "Av. Ángel Torcuato de Alvear 2470, Don Torcuato",
      horario: "Consultá en el local",
      tel: "",
      desc: "En el tramo comercial de Alvear.",
    },
    {
      id: "farmacia-jaskelson",
      nombre: "Farmacia Jaskelson",
      rubro: "Salud",
      dest: false,
      dir: "Don Torcuato",
      horario: "Consultá en el local",
      tel: "11 4748-7893",
      desc: "Teléfono publicado en directorios de farmacias de la localidad.",
    },
    {
      id: "farmacia-nueva-norte",
      nombre: "Farmacia Nueva Norte",
      rubro: "Salud",
      dest: false,
      dir: "Don Torcuato",
      horario: "Consultá en el local",
      tel: "11 4748-9990",
      desc: "Farmacia de la localidad con teléfono publicado.",
    },
    {
      id: "farmacia-balvi",
      nombre: "Farmacia Balvi (ex Hernández)",
      rubro: "Salud",
      dest: true,
      dir: "Gral. Pacheco 2728, Don Torcuato",
      horario: "Consultá si está de turno en el municipio",
      tel: "11 4748-2569",
      desc: "Apareció en el listado oficial de farmacias de turno de Tigre.",
    },
    {
      id: "farmacia-diaz",
      nombre: "Farmacia Díaz",
      rubro: "Salud",
      dest: false,
      dir: "Don Torcuato",
      horario: "Consultá en el local",
      tel: "11 4748-4493",
      desc: "También figura como ex Farmacia Solidaria.",
    },
    {
      id: "servi-net-comercio",
      nombre: "Servi-Net",
      rubro: "Informática",
      dest: true,
      dir: "Don Torcuato y Zona Norte",
      horario: "A domicilio y por WhatsApp",
      tel: "11 4030-6408",
      wa: "5491140306408",
      desc: "Redes, WiFi, fibra, cámaras y soporte de PC para casas y comercios.",
    },
  ],

  profesionales: [
    {
      id: "hdi-ferrara",
      nombre: "HDI Dr. Floreal Ferrara",
      oficio: "Hospital municipal de diagnóstico inmediato",
      rubro: "Salud",
      dest: true,
      busca: "hospital guardia pediatra medico diagnostico rayos",
      zona: "Colectora Oeste",
      dir: "Colectora Oeste esq. Menéndez y Pelayo, Don Torcuato",
      mat: "Municipal",
      tel: "11 4014-4484",
      wa: "5491126899228",
      desc: "Guardia y estudios. Turnos WhatsApp 11 2689-9228 y 11 2031-0388. Lun a vie 8 a 20 · Sáb 9 a 13.",
    },
    {
      id: "cs-don-torcuato",
      nombre: "Centro de Salud Don Torcuato",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      dest: true,
      busca: "medico centro de salud vacuna",
      zona: "Arata y España",
      dir: "Arata esquina España, Don Torcuato",
      mat: "Municipal",
      tel: "11 4513-2533",
      desc: "Centro municipal del casco. Consultá turnos en el centro.",
    },
    {
      id: "caps-belgrano",
      nombre: "CAPS Belgrano",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      dest: true,
      busca: "medico caps centro de salud",
      zona: "Belgrano",
      dir: "Gral. Belgrano 1661, Don Torcuato",
      mat: "Municipal",
      desc: "CAPS municipal. Confirmá horario en el centro.",
    },
    {
      id: "cs-baires",
      nombre: "Centro de Salud Baires",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      dest: false,
      busca: "medico barrio baires",
      zona: "Barrio Baires",
      dir: "Blandengues e/ Alvear y Ombú, B° Baires, Don Torcuato",
      mat: "Municipal",
      tel: "11 4513-2532",
      desc: "Centro municipal del barrio Baires.",
    },
    {
      id: "sagrado-corazon",
      nombre: "Clínica Sagrado Corazón",
      oficio: "Clínica privada",
      rubro: "Salud",
      dest: true,
      busca: "clinica privado guardia",
      zona: "Ruta 202 / Alvear",
      dir: "Av. Alvear 650, Don Torcuato",
      mat: "Privado",
      tel: "11 4741-7070",
      desc: "Clínica privada sobre Alvear. También 11 5263-3204.",
    },
    {
      id: "medigel",
      nombre: "Centro médico Medigel",
      oficio: "Consultorios",
      rubro: "Salud",
      dest: false,
      busca: "medico consultorio",
      zona: "Alvear",
      dir: "Av. Ángel Torcuato de Alvear, Don Torcuato",
      mat: "Consultorio",
      tel: "11 4748-7385",
      desc: "Centro médico con teléfono publicado sobre Alvear.",
    },
    {
      id: "odonto-siloe",
      nombre: "Odontología Siloe",
      oficio: "Odontología",
      rubro: "Salud",
      dest: true,
      busca: "dentista odontologo",
      zona: "Boulogne Sur Mer",
      dir: "Av. Boulogne Sur Mer, Don Torcuato",
      mat: "Consultorio",
      tel: "11 4727-3015",
      desc: "Consultorio odontológico con teléfono publicado.",
    },
    {
      id: "dental-total",
      nombre: "Dental Total",
      oficio: "Odontología",
      rubro: "Salud",
      dest: false,
      busca: "dentista odontologo",
      zona: "Almirante Brown",
      dir: "Almirante Brown, Don Torcuato",
      mat: "Consultorio",
      desc: "Consultorio sobre Almirante Brown. Confirmá el teléfono en el local.",
    },
    {
      id: "vet-centro",
      nombre: "Centro Médico Veterinario Don Torcuato",
      oficio: "Veterinaria",
      rubro: "Mascotas",
      dest: true,
      busca: "veterinario perro gato",
      zona: "Triunvirato",
      dir: "Triunvirato 1792, Don Torcuato",
      mat: "Veterinaria",
      tel: "11 4741-8555",
      desc: "Clínica veterinaria del casco. Algunos directorios también publican Av. Alvear 2079: llamá para confirmar.",
    },
    {
      id: "vet-polivet",
      nombre: "Veterinaria Polivet",
      oficio: "Veterinaria",
      rubro: "Mascotas",
      dest: false,
      busca: "veterinario",
      zona: "Riobamba",
      dir: "Riobamba 1819, Don Torcuato",
      mat: "Veterinaria",
      tel: "11 4741-4134",
      desc: "Veterinaria con domicilio y teléfono publicados.",
    },
    {
      id: "vet-gelp",
      nombre: "Veterinaria Dr. Gelp",
      oficio: "Veterinaria",
      rubro: "Mascotas",
      dest: false,
      busca: "veterinario",
      zona: "Triunvirato",
      dir: "Triunvirato 1685, Don Torcuato",
      mat: "Veterinaria",
      tel: "11 2057-2339",
      desc: "Consultorio veterinario sobre Triunvirato.",
    },
    {
      id: "servi-net",
      nombre: "Servi-Net",
      oficio: "Redes, informática y ciberseguridad",
      rubro: "Oficios",
      dest: true,
      busca: "redes wifi camaras computadora informatica tecnico pc fibra",
      zona: "Don Torcuato y Zona Norte",
      dir: "A domicilio",
      mat: "servi-net.com.ar",
      tel: "11 4030-6408",
      wa: "5491140306408",
      desc: "Redes, WiFi, fibra, servidores, cámaras y soporte de PC para casas y comercios.",
    },
  ],

  farmacias: {
    aviso:
      "El turno del día lo publica el Municipio de Tigre y cambia. Llamá antes de ir. Abajo, farmacias de Don Torcuato con dato publicado.",
    oficial: "https://www.tigre.gob.ar/salud/farmacias",
    oficialLabel: "Ver turno de hoy en Tigre",
  },

  clasificados: [
    {
      id: "cl-teatro",
      tipo: "Agenda",
      dest: true,
      titulo: "Teatro Municipal frente a Plaza Alvear",
      texto: "Estrada y Camacuá. 1.200 m² y sala para más de 250 espectadores. El municipio recorrió la obra el 7 de septiembre.",
      contacto: "Ver la nota",
      href: "articulo.html?id=teatro-municipal",
    },
    {
      id: "cl-921",
      tipo: "Agenda",
      dest: true,
      titulo: "Biblioteca móvil en el Jardín 921",
      texto: "Tigres Lectores entregó el 10 de septiembre el mueble «Entre Planetas» y libros infantiles.",
      contacto: "Ver la nota",
      href: "articulo.html?id=tigres-lectores",
    },
    {
      id: "cl-922",
      tipo: "Agenda",
      dest: false,
      titulo: "Jardín 922: SUM de 120 m² en obra",
      texto: "Salón de usos múltiples, cocina y patio. Recorrida municipal del 8 de septiembre.",
      contacto: "Ver la nota",
      href: "articulo.html?id=jardin-922",
    },
    {
      id: "cl-ubieto",
      tipo: "Agenda",
      dest: true,
      titulo: "Microestadio Ubieto, Riobamba 2497",
      texto: "Polideportivo San Martín. 1.600 m² y mil espectadores. Ya funciona para deporte y cultura.",
      contacto: "Ver la Agenda",
      href: "eventos.html",
    },
    {
      id: "cl-turno",
      tipo: "Servicio",
      dest: true,
      titulo: "Farmacias de turno de Tigre",
      texto: "El listado oficial cambia cada día. Castelli y Balvi aparecen en publicaciones municipales. Confirmá antes de salir.",
      contacto: "tigre.gob.ar/salud/farmacias",
      href: "farmacias.html",
    },
    {
      id: "cl-hdi",
      tipo: "Servicio",
      dest: true,
      titulo: "HDI Floreal Ferrara: turnos por WhatsApp",
      texto: "Colectora Oeste y Menéndez y Pelayo. WhatsApp 11 2689-9228 / 11 2031-0388.",
      contacto: "11 4014-4484",
      href: "profesionales.html",
    },
    {
      id: "cl-empleo-rrhh",
      tipo: "Empleo",
      dest: true,
      titulo: "Analista de RRHH en Don Torcuato",
      texto: "Publicado en ZonaJobs (agosto 2026). Logística, lunes a viernes 9 a 18, modalidad híbrida. Buscá el aviso vigente.",
      contacto: "ZonaJobs · aviso 2187319",
    },
    {
      id: "cl-empleo-sistemas",
      tipo: "Empleo",
      dest: false,
      titulo: "Implementador de sistemas / líder de proyectos",
      texto: "Búsqueda de ADN Recursos Humanos para empresa en Don Torcuato. Lun a vie 8 a 17, monotributo. Vigencia publicada hasta el 28 de septiembre.",
      contacto: "ADN Recursos Humanos",
    },
    {
      id: "cl-empleo-deposito",
      tipo: "Empleo",
      dest: false,
      titulo: "Operario y administrativo de depósito",
      texto: "Apertura de unidad en Zona Norte / Don Torcuato. Carga, stock y documentación. Secundario y experiencia. Publicado en portales de empleo.",
      contacto: "Portales de empleo · Don Torcuato",
    },
    {
      id: "cl-empleo-contable",
      tipo: "Empleo",
      dest: false,
      titulo: "Analista contable jr y otros oficios",
      texto: "Computrabajo lista decenas de avisos en Don Torcuato: contable, tablerista, técnico de campo, depósito y ventas. Revisá la fecha del aviso.",
      contacto: "Computrabajo · Don Torcuato",
    },
    {
      id: "cl-alquiler",
      tipo: "Alquiler",
      dest: false,
      titulo: "Departamentos y casas en alquiler",
      texto: "Hay avisos vigentes de 1 a 3 ambientes en portales (Zonaprop y similares). No publicamos precios viejos: mirá el aviso del día.",
      contacto: "Zonaprop · Don Torcuato",
    },
    {
      id: "cl-servinet",
      tipo: "Servicio",
      dest: true,
      titulo: "Redes, WiFi y PCs a domicilio",
      texto: "Servi-Net: fibra, cámaras, servidores y soporte para casas y comercios del barrio.",
      contacto: "11 4030-6408",
      href: "profesionales.html",
    },
    {
      id: "cl-vet",
      tipo: "Servicio",
      dest: false,
      titulo: "Veterinarias del casco",
      texto: "Centro Médico Veterinario, Triunvirato 1792, 11 4741-8555. También Polivet (Riobamba 1819) y Dr. Gelp (Triunvirato 1685).",
      contacto: "Ver profesionales",
      href: "profesionales.html",
    },
    {
      id: "cl-publicar",
      tipo: "Se ofrece",
      dest: true,
      titulo: "Publicá tu clasificado de Don Torcuato",
      texto: "Se busca, se alquila, empleo o servicio. Nombre, rubro y WhatsApp. No inventamos avisos de vecinos.",
      contacto: "Escribir a la revista",
      href: "contacto.html",
    },
    {
      id: "cl-ficha",
      tipo: "Se ofrece",
      dest: false,
      titulo: "Sumá tu ficha al índice",
      texto: "Comercio, consultorio u oficio con dirección publicada. Entra al buscador y al índice A–Z.",
      contacto: "Pedir un espacio",
      href: "anunciantes.html",
    },
  ],

  eventos: [
    {
      id: "e1",
      fecha: "7 sep",
      hora: "Recorrida municipal",
      titulo: "Supervisión de obra del Teatro Municipal",
      lugar: "Estrada y Camacuá, frente a Plaza Alvear",
      desc: "1.200 m² y sala para más de 250 espectadores. El municipio recorrió el predio.",
    },
    {
      id: "e2",
      fecha: "8 sep",
      hora: "Por la mañana",
      titulo: "Obras en el Jardín 922 y la Primaria 45",
      lugar: "Jardín N° 922 · Escuela Primaria N° 45",
      desc: "SUM de 120 m², cocina y patio en el jardín. Comedor terminado en la 45.",
    },
    {
      id: "e3",
      fecha: "10 sep",
      hora: "Mañana",
      titulo: "Tigres Lectores en el Jardín 921",
      lugar: "Jardín de Infantes N° 921",
      desc: "Taller de lectura y entrega de biblioteca móvil «Entre Planetas, con un Libro en la Mano».",
    },
    {
      id: "e4",
      fecha: "Todo el mes",
      hora: "Según programación",
      titulo: "Microestadio Intendente Ricardo Ubieto",
      lugar: "Polideportivo San Martín, Riobamba 2497",
      desc: "1.600 m² y mil espectadores. Deporte y cultura. Confirmá la fecha en el municipio.",
    },
    {
      id: "e5",
      fecha: "Todos los días",
      hora: "Consultá el municipio",
      titulo: "Farmacias de turno",
      lugar: "tigre.gob.ar/salud/farmacias",
      desc: "El listado cambia. Llamá a la farmacia antes de ir.",
    },
  ],

  paquetes: [
    {
      id: "clasificado",
      nombre: "Clasificado",
      precio: "Consultar",
      detalle: "Como en el papel: 40 palabras, una categoría y teléfono. Sale en la web y en el envío.",
      items: ["Se busca / Alquiler / Servicio / Empleo", "Teléfono o WhatsApp", "15 días", "Entra al índice si es destacado"],
    },
    {
      id: "ficha",
      nombre: "Ficha en el índice",
      precio: "Consultar",
      detalle: "Tu nombre en el índice de anunciantes, con rubro y contacto.",
      items: ["Orden alfabético", "Rubro", "WhatsApp", "Link a tu ficha"],
    },
    {
      id: "destacado",
      nombre: "Módulo de edición",
      precio: "Consultar",
      detalle: "Recuadro en la sección (comercios, profesionales o clasificados).",
      items: ["Diseño incluido", "Prioridad en el listado", "Mención en el mail", "Un mes"],
    },
    {
      id: "portada",
      nombre: "Destacado de portada",
      precio: "Consultar",
      detalle: "La primera impresión de quien abre la revista o el enlace.",
      items: ["Home + edición", "Índice destacado", "Envío WhatsApp", "Reporte de clics"],
    },
  ],

  anunciantes: [
    { nombre: "Farmacia Magnin", rubro: "Salud", tipo: "Destacado", seccion: "Comercios", tel: "11 4748-4605" },
    { nombre: "Farmacia Castelli", rubro: "Salud", tipo: "Turno", seccion: "Comercios", tel: "11 4748-0460" },
    { nombre: "HDI Floreal Ferrara", rubro: "Salud", tipo: "Ficha", seccion: "Profesionales", tel: "11 4014-4484" },
    { nombre: "Servi-Net", rubro: "Oficios", tipo: "Ficha", seccion: "Profesionales", tel: "11 4030-6408" },
    { nombre: "Centro Médico Veterinario Don Torcuato", rubro: "Mascotas", tipo: "Ficha", seccion: "Profesionales", tel: "11 4741-8555" },
    { nombre: "Odontología Siloe", rubro: "Salud", tipo: "Ficha", seccion: "Profesionales", tel: "11 4727-3015" },
  ],
};
